export const ALL_BLOGS_REQUEST = "ALL_BLOGS_REQUEST";
export const ALL_BLOGS_SUCCESS = "ALL_BLOGS_SUCCESS";
export const ALL_BLOGS_FAIL = "ALL_BLOGS_FAIL";

export const USER_BLOGS_REQUEST = "USER_BLOGS_REQUEST";
export const USER_BLOGS_SUCCESS = "USER_BLOGS_SUCCESS";
export const USER_BLOGS_FAIL = "USER_BLOGS_FAIL";

export const CREATE_BLOGS_REQUEST = "CREATE_BLOGS_REQUEST";
export const CREATE_BLOGS_SUCCESS = "CREATE_BLOGS_SUCCESS";
export const CREATE_BLOGS_FAIL = "CREATE_BLOGS_FAIL";

export const DELETE_BLOGS_REQUEST = "DELETE_BLOGS_REQUEST";
export const DELETE_BLOGS_SUCCESS = "DELETE_BLOGS_SUCCESS";
export const DELETE_BLOGS_RESET = "DELETE_BLOGS_RESET";
export const DELETE_BLOGS_FAIL = "DELETE_BLOGS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
